[package]
name = "sp-mac-eq-kvac"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "benchmark"
path = "bin/benchmark.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-bls12-381 = "0.5.0-alpha.0"
ark-ed25519 = "0.5.0-alpha.0"
ark-secp256k1 = "0.5.0-alpha.0"
ark-std = "0.5.0-alpha.0"
ark-poly = "0.5.0-alpha.0"
rand = "0.8.5"
ark-ec = "0.5.0-alpha.0"
ark-ff = "0.5.0-alpha.0"
anyhow = "1.0.75"
ark-serialize = "0.5.0-alpha.0"
hex = "0.4.3"
sha2 = { version = "0.10.8", default-features = false }